### ISSUE TITLE
Double digest not reporting all cut sites

### ISSUE THREAD

**Issue by berge2015** [JINPENG-WANG/RestrictionDigest#4]
Dear Jinpeng,

First of all thanks a lot for this magnificent module. It is a very fast and powerful tool.

Now to the issue: suppose that I have enzyme A and enzyme B as two cutters on my sequences. If A cuts at 5 bp and 10 bp, and B cuts at 8 bp and 15 bp, your script reports only these two cut fragments: A5-B8 & A10-B15.

However, in biology, we also expect the cut fragments A5-B15 and A10-B8 (on the - strand). So I was wondering if there is any way to obtain ALL the cut sites, and not just the adjacent ones. I hope I was able to explain the scenario clearly.

As for the command I am using, I am using your double digest script example from the paper with the following change in step 5: $double_digest->change_range(-start =>40,-end =>200);

Edit: This issue is also true for single cutters. For example, if A cuts at 5 bp, 10 bp, 20 bp, and 30 bp, then the fragments reported are A5-A10, A20-A30. The fragments A5-A20, A5-A30, A10-A20, A10-A30 are completely missing. I have attached the last columns of the PstI cutter to explain the issue more clearly. Thank you.

![untitled](https://cloud.githubusercontent.com/assets/22395323/18787083/41f8680c-816f-11e6-91f1-10d18c9db864.png)

**Comment by JINPENG-WANG** [comment]
Dear berge2015,

Thank you very much for your comment.  

I think I have got what you mean.  Let me address the main function of RestrictionDigest. It is designed to simulate the complete digestion of the genome DNA by endonucleases. That is to say, we assume that every cut site in the genome is recognized and cut by the enzyme(s), which would generate the shortest fragments. As in the example you listed out (A cuts at 5 bp and 10 bp, B cuts at 8 bp and 15 bp), there will be only A5-B8, B8-A10 and A10-B15. Other fragments, like A5-A10, A5-A15 and B8-B15, are not available.  In my test, the A10-B8 (on the negative strand) type fragments are availabe. The picture below lists part of fragments generated by EcoRI and PstI. Almost half of them are located in the negative strand.  
![image](https://cloud.githubusercontent.com/assets/11345310/18812366/917febb6-8304-11e6-9d59-47500a1a1b4a.png)
The commands for the double enzymes digestion I used are listed below:
                _# For double enzymes digestion
                my $digest=RestricionDigest::SingleItem::Double->new();
                # Provide the two enzyems to be used.
                $digest->add_enzyme_pair(-front_enzyme=>"EcoRI", -behind_enzyme=>"PstI");
                # Execute the simulation.
                $digest->double_digest;_

For the single enzyme digestion, RestrictionDigest still generates the shortest fragments. In the sinlge enzyem digestion by Pst  you listed out, I realized that you may have used  "Double" object instead of "Single". For the single enzyme digestion, the commands are listed below:
              _my $digest=RestrictionDigest::SingleItem::Single->new();
              $digest->add_single_enzyme(-enzyme=>"PstI");
              $digest->single_digest;_

If commands listed below were used for single enzyme digestion, only fragments on the plus strand will be generated:
             _my $digest=RestrictionDigest::SingleItem::Double->new();
             $digest->add_enzyme_pair(-front_enzyme=>"PstI", -behind_enzyme=>"PstI");
             $digest->double_digest;_

I am sorry for that this module cannot provide all possible fragments.  Another module or script must be writen to ahieve this purpose.

**Comment by JINPENG-WANG** [comment]
Another comment on the ALL fragments is the large number of all possible fragments. If there were 1 000 cut sites on one chromosome, there will be ![image](https://cloud.githubusercontent.com/assets/11345310/18812615/c9587816-830c-11e6-8911-310534a610b3.png) (499,500) possible fragments. If there were 10,000 cut sites, there will be 49,995,000 fragments. Maybe the program will work slow.

**Comment by berge2015** [comment]
Sorry about my picture with PstI cuts on + strand only... this was only meant to be an example. For my real work, I do use the Single digest. 

You are right about the number of cuts being too large if ALL cuts are reported. Besides, reporting ALL cut fragments might not be too practical either if the fragments are too large to be sample even in biological process... think of fragments > few Kb in size. These may not be worth going after anyway. For double digest, all number of cuts would be n(Enzyme1) x m(Enzyme2) = massive numbers to report.

Lastly, I compared your results with that from CPAN's Bio::Restriction::Analysis (using Bio::Restriction::EnzymeCollection) and the results are pretty much the same. I think the choice of reporting adjacent cuts is mainly to manage the large number of cuts.

Thank you for writing back so quickly with a clear explanation.

**Comment by JINPENG-WANG** [comment]
You are welcome. And thank you for using this module.
